KFSearch:
  # Name of model to use for searching
  model: KFSearch
  filters:
    # Mapping from filter name -> param name
    query: kw
    sort: sort
    direction: dir
    page: page
    product: p
    category: c
  # Where ajax searches end up
  endpoint: /ci/ajaxRequest/search
OKCSSearch:
  model: OkcsSearch
  filters:
    query: kw
    locale: loc
    facet: facet
    direction: dir
    page: page
    truncate: truncate
    searchType: searchType
    okcsSearchSession: okcsSearchSession
    priorTransactionID: priorTransactionID
    transactionID: transactionID
    okcsNewSearch: okcsNewSearch
    prod: product
    cat: category
  endpoint: /ci/ajaxRequest/search
OKCSBrowse:
  model: OkcsBrowse
  filters:  
    page: page
  endpoint: /ci/okcsAjaxRequest/getOkcsData